# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: skywalk
      url-base: https://github.com/skywalk-software

  projects:
    - name: zephyr
      remote: skywalk
      revision: feature/lsm6dsl_lis3mdl
      import: true
